version: '3'

vars:
  CA_BUNDLE: /etc/ssl/ca-bundle.pem
  GROUP_BIN: '{{.GROUP_HOME}}/bin'
  GROUP_CONTAINERS: '{{.GROUP_HOME}}/containers'
  GROUP_MODULEFILES: '{{.GROUP_HOME}}/Modules/modulefiles'
  OPT_DIR: '{{.GROUP_HOME}}/opt'

includes:
  bedtools: ./bedtools.yml
  blast: ./BLAST.yml
  bowtie2: ./Bowtie2.yml
  bracken: ./Bracken.yml
  clonalframeml: ./ClonalFrameML.yml
  csvkit: ./csvkit.yml
  duckdb: ./DuckDB.yml
  jq: ./jq.yml
  kraken2: ./Kraken2.yml
  micromamba: ./Micromamba.yml
  ncbi-datasets: ./NCBIDatasetsCLI.yml
  ncurses: ./Ncurses.yml
  nextflow: ./Nextflow.yml
  python: ./Python.yml
  raxml-ng: ./RAxML-NG.yml
  rust: ./Rust.yml
  samtools-legacy: ./SAMtools-legacy.yml
  samtools-bcftools-htslib: ./SAMtools-bcftools-htslib.yml
  snakemake: ./Snakemake.yml
  snpsites: ./SNPsites.yml
  srst2: ./SRST2.yml
  taskfile: ./Task.yml
  tinytex: ./TinyTex.yml
  uv: ./uv.yml
  vg: ./vg.yml
  vcf2parquet: ./vcf2parquet.yml
  yq: ./yq.yml

tasks:
  default:
    - task: core

  all:
    - task: bedtools
    - task: blast
    - task: bowtie2
    - task: bracken
    - task: clonalframeml
    - task: csvkit
    - task: duckdb
    - task: jq
    - task: kraken2
    - task: micromamba
    - task: ncbi-datasets
    - task: ncurses
    - task: nextflow
    - task: python
    - task: raxml-ng
    - task: rust
    - task: samtools-legacy
    - task: samtools-bcftools-htslib
    - task: snakemake
    - task: snpsites
    - task: srst2
    - task: taskfile
    - task: tinytex
    - task: uv
    - task: vcf2parquet
    - task: vg
    - task: yq

  core:
    - task: bedtools
    - task: blast
    - task: bowtie2
    - task: bracken
    - task: csvkit
    - task: duckdb
    - task: jq
    - task: kraken2
    - task: micromamba
    - task: ncbi-datasets
    - task: ncurses
    - task: nextflow
    - task: python
    - task: raxml-ng
    - task: rust
    - task: samtools-legacy
    - task: samtools-bcftools-htslib
    - task: snakemake
    - task: snpsites
    - task: srst2
    - task: taskfile
    - task: tinytex
    - task: uv
    - task: vcf2parquet
    - task: yq

  # ~*~

  bedtools:
    - task: bedtools:install
      vars:
        HTSLIB_VERSION: '{{.HTSLIB_VERSION | default "1.20"}}'
        PYTHON_VERSION: '{{.PYTHON_VERSION | default "3.12.4"}}'
        VERSION: '{{.VERSION | default "2.31.1"}}'

  blast:
    - task: blast:install
      vars:
        VERSION: '{{.VERSION | default "2.16.0"}}'

  bowtie2:
    - task: bowtie2:install
      vars:
        VERSION: '{{.VERSION | default "2.1.0"}}'

  bracken:
    - task: bracken:install
      vars:
        VERSION: '{{.VERSION | default "2.9"}}'
        KRAKEN2_VERSION: '{{.KRAKEN2_VERSION | default "2.1.3"}}'

  clonalframeml:
    - task: clonalframeml:install
      vars:
        VERSION: '{{.VERSION | default "1.13"}}'

  csvkit:
    - task: csvkit:install
      vars:
        PYTHON_VERSION: '{{.PYTHON_VERSION | default "3.12.4"}}'
        UV_VERSION: '{{.UV_VERSION | default "0.4.26"}}'
        VERSION: '{{.VERSION | default "2.0.1"}}'

  duckdb:
    - task: duckdb:install
      vars:
        VERSION: '{{.VERSION | default "1.1.2"}}'
    - task: duckdb:install-nightly

  jq:
    - task: jq:install
      vars:
        VERSION: '{{.VERSION | default "1.7.1"}}'

  kraken2:
    - task: kraken2:install
      vars:
        VERSION: '{{.VERSION | default "2.1.3"}}'

  micromamba:
    - task: micromamba:install
      vars:
        VERSION: '{{.VERSION | default "2.0.1-0"}}'

  ncbi-datasets:
    - task: ncbi-datasets:install
      vars:
        VERSION_CLI: '{{.VERSION_CLI | default "16.29.0"}}'
        VERSION_DOCS: '{{.VERSION_DOCS | default "16.30.0"}}'

  ncurses:
    - task: ncurses:install
      vars:
        VERSION: '{{.VERSION | default "6.5"}}'

  nextflow:
    - task: nextflow:install
      vars:
        VERSION: '{{.VERSION | default "24.04.4"}}'

  python:
    desc: Install Python
    summary: |
      Notes:
        - `pip` for Python2 is no longer supported.
    vars:
      VERSION: '{{.VERSION | default "3.12.4 2.7.5"}}'
      VERSIONS: '{{.VERSIONS | default .VERSION}}'
    cmds:
      - for: { var: VERSIONS }
        task: python:install
        vars:
          VERSION: '{{.ITEM}}'

  raxml-ng:
    - task: raxml-ng:install
      vars:
        VERSION: '{{.VERSION | default "1.2.2"}}'

  rust:
    - task: rust:install
      vars:
        VERSION: '{{.VERSION | default "1.82.0"}}'

  samtools-bcftools-htslib:
    - task: samtools-bcftools-htslib:install
      vars:
        VERSION: '{{.VERSION | default "1.20"}}'

  samtools-legacy:
    - task: samtools-legacy:install
      vars:
        NCURSES_VERSION: '{{.NCURSES_VERSION | default "6.5"}}'
        VERSION: '{{.VERSION | default "0.1.18"}}'

  snakemake:
    - task: snakemake:install
      vars:
        MICROMAMBA_VERSION: '{{.MICROMAMBA_VERSION | default "2.0.1-0"}}'
        VERSION: '{{.VERSION | default "8.16"}}'

  snpsites:
    - task: snpsites:install
      vars:
        VERSION: '{{.VERSION | default "2.5.1"}}'

  srst2:
    - task: srst2:install
      vars:
        BOWTIE2_VERSION: '{{.BOWTIE2_VERSION | default "2.1.0"}}'
        SAMTOOLS_VERSION: '{{.SAMTOOLS_VERSION | default "0.1.18"}}'
        VERSION: '{{.VERSION | default "0.2.0"}}'

  taskfile:
    - task: taskfile:install
      vars:
        VERSION: '{{.VERSION | default "3.39.2"}}'

  tinytex:
    - task: tinytex:install
      vars:
        VERSION: '{{.VERSION | default "2024.07.03"}}'

  uv:
    - task: uv:install
      vars:
        RUST_VERSION: '{{.RUST_VERSION | default "1.82.0"}}'
        VERSION: '{{.VERSION | default "0.4.26"}}'

  vcf2parquet:
    - task: vcf2parquet:install
      vars:
        MICROMAMBA_VERSION: '{{.MICROMAMBA_VERSION | default "2.0.1-0"}}'
        VERSION: '{{.VERSION | default "0.4.1"}}'

  vg:
    - task: vg:install
      vars:
        VERSION: '{{.VERSION | default "1.60.0"}}'

  yq:
    - task: yq:install
      vars:
        VERSION: '{{.VERSION | default "4.44.3"}}'