version: '3'

vars:
  CA_BUNDLE: /etc/ssl/ca-bundle.pem
  GROUP_BIN: '{{.GROUP_HOME}}/bin'
  GROUP_CONTAINERS: '{{.GROUP_HOME}}/containers'
  GROUP_MODULEFILES: '{{.GROUP_HOME}}/Modules/modulefiles'
  OPT_DIR: '{{.GROUP_HOME}}/opt'

includes:
  # aria2: ./Aria2.yml
  # ariba: ./ARIBA.yml
  bedtools: ./bedtools.yml
  blast: ./BLAST.yml
  bowtie2: ./Bowtie2.yml
  bracken: ./Bracken.yml
  # cdhit: ./CD-HIT.yml
  csvkit: ./csvkit.yml
  # cutadapt: ./Cutadapt.yml
  # d4tools: ./D4.yml
  # direnv: ./direnv.yml
  duckdb: ./DuckDB.yml
  # fasttree: ./FastTree.yml
  # figtree: ./FigTree.yml
  # gatk: ./GATK.yml
  # ggtree: ./ggtree.yml
  # gnumeric: ./Gnumeric.yml
  # gubbins: ./Gubbins.yml
  # igv-reports: ./igv-reports.yml
  jq: ./jq.yml
  # kma: ./KMA.yml
  # kmerresistance: ./KmerResistance.yml
  kraken2: ./Kraken2.yml
  # krakenuniq: ./KrakenUniq.yml
  # kronatools: ./KronaTools.yml
  # lz4: ./LZ4.yml
  # magic-blast: ./Magic-BLAST.yml
  micromamba: ./Micromamba.yml
  # mlst: ./mlst.yml
  # mosdepth: ./mosdepth.yml
  # mummer: ./MUMmer.yml
  ncbi-datasets: ./NCBIDatasetsCLI.yml
  ncurses: ./Ncurses.yml
  nextflow: ./Nextflow.yml
  # nim: ./Nim.yml
  # pandoc: ./Pandoc.yml
  # perl: ./Perl.yml
  # pygenometracks: ./pyGenomeTracks.yml
  python: ./Python.yml
  # qsv: ./qsv.yml
  raxml-ng: ./RAxML-NG.yml
  # resfinder: ./ResFinder.yml
  rust: ./Rust.yml
  samtools-legacy: ./SAMtools-legacy.yml
  samtools-bcftools-htslib: ./SAMtools-bcftools-htslib.yml
  # sickle: ./Sickle.yml
  snakemake: ./Snakemake.yml
  snpsites: ./SNPsites.yml
  # spades: ./SPAdes.yml
  # sratoolkit: ./SRAToolkit.yml
  srst2: ./SRST2.yml
  taskfile: ./Task.yml
  # termshot: ./termshot.yml
  tinytex: ./TinyTex.yml
  uv: ./uv.yml
  vcf2parquet: ./vcf2parquet.yml
  # vcftools: ./VCFtools.yml
  # veryfasttree: ./VeryFastTree.yml
  # yadm: ./yadm.yml
  yq: ./yq.yml

# TODO: Better version management (via env dotfile?)

tasks:
  default:
    - task: core

  # all:
  #   - task: aria2
  #   - task: ariba
  #   - task: bedtools
  #   - task: blast
  #   - task: bowtie2
  #   - task: bracken
  #   - task: cdhit
  #   - task: csvkit
  #   - task: cutadapt
  #   - task: d4tools
  #   - task: direnv
  #   - task: duckdb
  #   - task: fasttree
  #   - task: figtree
  #   - task: gatk
  #   - task: ggtree
  #   - task: gnumeric
  #   - task: gubbins
  #   - task: igv-reports
  #   - task: jq
  #   - task: kma
  #   - task: kmerresistance
  #   - task: kraken2
  #   - task: krakenuniq
  #   - task: kronatools
  #   - task: lz4
  #   - task: magic-blast
  #   - task: micromamba
  #   - task: mlst
  #   - task: mosdepth
  #   - task: mummer
  #   - task: ncbi-datasets
  #   - task: ncurses
  #   - task: nim
  #   - task: pandoc
  #   - task: perl
  #   - task: pygenometracks
  #   - task: python
  #   - task: qsv
  #   - task: raxml-ng
  #   - task: resfinder
  #   - task: rust
  #   - task: samtools-legacy
  #   - task: samtools-bcftools-htslib
  #   - task: sickle
  #   - task: snakemake
  #   - task: snpsites
  #   - task: spades
  #   - task: sratoolkit
  #   - task: srst2
  #   - task: taskfile
  #   - task: termshot
  #   - task: tinytex
  #   - task: uv
  #   - task: vcf2parquet
  #   - task: vcftools
  #   - task: veryfasttree
  #   - task: yadm
  #   - task: yq

  # ~*~

  core:
    - task: bedtools
    - task: blast
    - task: bowtie2
    - task: bracken
    - task: csvkit
    - task: duckdb
    - task: jq
    - task: kraken2
    - task: micromamba
    - task: ncbi-datasets
    - task: ncurses
    - task: nextflow
    - task: python
    - task: raxml-ng
    - task: rust
    - task: samtools-legacy
    - task: samtools-bcftools-htslib
    - task: snakemake
    - task: snpsites
    - task: srst2
    - task: taskfile
    - task: tinytex
    - task: uv
    - task: vcf2parquet
    - task: yq

  # bio:
  #   - task: ariba
  #   - task: bedtools
  #   - task: blast
  #   - task: bowtie2
  #   - task: bracken
  #   - task: cdhit
  #   - task: cutadapt
  #   - task: d4tools
  #   - task: fasttree
  #   - task: figtree
  #   - task: gatk
  #   - task: ggtree
  #   - task: gubbins
  #   - task: igv-reports
  #   - task: kma
  #   - task: kmerresistance
  #   - task: kraken2
  #   - task: krakenuniq
  #   - task: kronatools
  #   - task: magic-blast
  #   - task: mlst
  #   - task: mosdepth
  #   - task: mummer
  #   - task: ncbi-datasets
  #   - task: pygenometracks
  #   - task: raxml-ng
  #   - task: resfinder
  #   - task: samtools-legacy
  #   - task: samtools-bcftools-htslib
  #   - task: sickle
  #   - task: snpsites
  #   - task: spades
  #   - task: sratoolkit
  #   - task: srst2
  #   - task: veryfasttree
  #   - task: vcf2parquet
  #   - task: vcftools

  # admin:
  #   - task: yadm

  # data:
  #   - task: csvkit
  #   - task: d4tools
  #   - task: duckdb
  #   - task: gnumeric
  #   - task: jq
  #   - task: qsv
  #   - task: yq

  # utils:
  #   - task: aria2
  #   - task: direnv
  #   - task: lz4
  #   - task: micromamba
  #   - task: ncurses
  #   - task: pandoc
  #   - task: snakemake
  #   - task: taskfile
  #   - task: termshot
  #   - task: tinytex
  #   - task: uv

  # interpreters:
  #   - task: perl
  #   - task: python

  # compilers:
  #   - task: nim
  #   - task: rust

  # kraken-suite:
  #   desc: Install Kraken software suite
  #   summary: |
  #     Install Kraken software suite

  #     The Kraken suite is an end-to-end pipeline for the classification, 
  #     quantification and visualization of metagenomic datasets.

  #     URLs
  #     ----
  #       - https://doi.org/10.1038/s41596-022-00738-y
  #       - https://ccb.jhu.edu/data/kraken2_protocol/
  #       - https://github.com/martin-steinegger/kraken-protocol/
  #   cmds:
  #     - task: kraken2
  #     - task: bracken
  #     # - task: krakentools
  #     # - task: pavian
  #     - task: bowtie2

  # ~*~

  # aria2:
  #   - task: aria2:install
  #     vars:
  #       VERSION: '{{.VERSION | default "1.37.0"}}'

  # ariba:
  #   - task: ariba:install

  bedtools:
    - task: bedtools:install
      vars:
        HTSLIB_VERSION: '{{.HTSLIB_VERSION | default "1.20"}}'
        PYTHON_VERSION: '{{.PYTHON_VERSION | default "3.12.4"}}'
        VERSION: '{{.VERSION | default "2.31.1"}}'

  blast:
    - task: blast:install
      vars:
        VERSION: '{{.VERSION | default "2.16.0"}}'

  bowtie2:
    - task: bowtie2:install
      vars:
        VERSION: '{{.VERSION | default "2.1.0"}}'

  bracken:
    - task: bracken:install
      vars:
        VERSION: '{{.VERSION | default "2.9"}}'
        KRAKEN2_VERSION: '{{.KRAKEN2_VERSION | default "2.1.3"}}'

  # cdhit:
  #   - task: cdhit:install

  csvkit:
    - task: csvkit:install
      vars:
        PYTHON_VERSION: '{{.PYTHON_VERSION | default "3.12.4"}}'
        UV_VERSION: '{{.UV_VERSION | default "0.4.26"}}'
        VERSION: '{{.VERSION | default "2.0.1"}}'

  # cutadapt:
  #   - task: cutadapt:install

  # d4tools:
  #   - task: d4tools:install

  # direnv:
  #   - task: direnv:install

  duckdb:
    - task: duckdb:install
      vars:
        VERSION: '{{.VERSION | default "1.1.2"}}'
    - task: duckdb:install-nightly

  # fasttree:
  #   - task: fasttree:install
  #   - task: fasttree:install_dbl
  #   - task: fasttree:install_openmp

  # figtree:
  #   - task: figtree:install

  # gatk:
  #   - task: gatk:install

  # ggtree:
  #   - task: ggtree:install
  #     vars:
  #       VERSION: '{{.VERSION | default "3.19"}}'

  # gnumeric:
  #   - task: gnumeric:install

  # gubbins:
  #   - task: gubbins:install

  # igv-reports:
  #   - task: igv-reports:install
  #     vars:
  #       VERSION: '{{.VERSION | default "1.12.0"}}'

  jq:
    - task: jq:install
      vars:
        VERSION: '{{.VERSION | default "1.7.1"}}'

  # kma:
  #   - task: kma:install

  # kmerresistance:
  #   - task: kmerresistance:install

  kraken2:
    - task: kraken2:install
      vars:
        VERSION: '{{.VERSION | default "2.1.3"}}'

  # krakenuniq:
  #   - task: krakenuniq:install

  # kronatools:
  #   - task: kronatools:install

  # lz4:
  #   - task: lz4:install

  # magic-blast:
  #   - task: magic-blast:install

  micromamba:
    - task: micromamba:install
      vars:
        VERSION: '{{.VERSION | default "2.0.1-0"}}'

  # mlst:
  #   - task: mlst:install

  # mosdepth:
  #   - task: mosdepth:install

  # mummer:
  #   - task: mummer:install

  ncbi-datasets:
    - task: ncbi-datasets:install
      vars:
        VERSION_CLI: '{{.VERSION_CLI | default "16.29.0"}}'
        VERSION_DOCS: '{{.VERSION_DOCS | default "16.30.0"}}'

  ncurses:
    - task: ncurses:install
      vars:
        VERSION: '{{.VERSION | default "6.5"}}'

  nextflow:
    - task: nextflow:install
      vars:
        VERSION: '{{.VERSION | default "24.04.4"}}'

  # nim:
  #   - task: nim:install

  # pandoc:
  #   - task: pandoc:install

  # perl:
  #   vars:
  #     VERSION: '{{.VERSION | default "5.40.0 5.24.4"}}'
  #     VERSIONS: '{{.VERSIONS | default .VERSION}}'
  #   cmds:
  #     - for: { var: VERSIONS }
  #       task: perl:install
  #       vars:
  #         VERSION: '{{.ITEM}}'

  # pygenometracks:
  #   - task: pygenometracks:install
  #     vars:
  #       VERSION: '{{.VERSION | default "3.9"}}'

  python:
    desc: Install Python
    summary: |
      Notes:
        - `pip` for Python2 is no longer supported.
    vars:
      VERSION: '{{.VERSION | default "3.12.4 2.7.5"}}'
      VERSIONS: '{{.VERSIONS | default .VERSION}}'
    cmds:
      - for: { var: VERSIONS }
        task: python:install
        vars:
          VERSION: '{{.ITEM}}'

  # qsv:
  #   - task: qsv:install
  #     vars:
  #       VERSION: '{{.VERSION | default "0.89.0"}}'

  raxml-ng:
    - task: raxml-ng:install
      vars:
        VERSION: '{{.VERSION | default "1.2.2"}}'

  # resfinder:
  #   - task: resfinder:install

  rust:
    - task: rust:install
      vars:
        VERSION: '{{.VERSION | default "1.82.0"}}'

  samtools-bcftools-htslib:
    - task: samtools-bcftools-htslib:install
      vars:
        VERSION: '{{.VERSION | default "1.20"}}'

  samtools-legacy:
    - task: samtools-legacy:install
      vars:
        NCURSES_VERSION: '{{.NCURSES_VERSION | default "6.5"}}'
        VERSION: '{{.VERSION | default "0.1.18"}}'

  # sickle:
  #   - task: sickle:install

  snakemake:
    - task: snakemake:install
      vars:
        MICROMAMBA_VERSION: '{{.MICROMAMBA_VERSION | default "2.0.1-0"}}'
        VERSION: '{{.VERSION | default "8.16"}}'

  snpsites:
    - task: snpsites:install
      vars:
        VERSION: '{{.VERSION | default "2.5.1"}}'

  # spades:
  #   - task: spades:install

  # sratoolkit:
  #   - task: sratoolkit:install

  srst2:
    - task: srst2:install
      vars:
        BOWTIE2_VERSION: '{{.BOWTIE2_VERSION | default "2.1.0"}}'
        SAMTOOLS_VERSION: '{{.SAMTOOLS_VERSION | default "0.1.18"}}'
        VERSION: '{{.VERSION | default "0.2.0"}}'

  taskfile:
    - task: taskfile:install
      vars:
        VERSION: '{{.VERSION | default "3.39.2"}}'

  # termshot:
  #   - task: termshot:install

  tinytex:
    - task: tinytex:install
      vars:
        VERSION: '{{.VERSION | default "2024.07.03"}}'

  uv:
    - task: uv:install
      vars:
        RUST_VERSION: '{{.RUST_VERSION | default "1.82.0"}}'
        VERSION: '{{.VERSION | default "0.4.26"}}'

  vcf2parquet:
    - task: vcf2parquet:install
      vars:
        MICROMAMBA_VERSION: '{{.MICROMAMBA_VERSION | default "2.0.1-0"}}'
        VERSION: '{{.VERSION | default "0.4.1"}}'

  # vcftools:
  #   - task: vcftools:install

  # veryfasttree:
  #   - task: veryfasttree:install_py

  # yadm:
  #   - task: yadm:install

  yq:
    - task: yq:install
      vars:
        VERSION: '{{.VERSION | default "4.44.3"}}'