version: '3'

vars:
  # Installation accessories
  CA_BUNDLE: /etc/ssl/ca-bundle.pem
  
  # Group directories
  GROUP_BIN: '{{.GROUP_HOME}}/bin'
  GROUP_CONTAINERS: '{{.GROUP_HOME}}/containers'
  GROUP_MODULEFILES: '{{.GROUP_HOME}}/Modules/modulefiles'
  OPT_DIR: '{{.GROUP_HOME}}/opt'

  # Software defaults
  DEFAULT_PYTHON: '{{.OPT_DIR}}/python/3.12.4/bin/python'

  # Environment module defaults
  DEFAULT_JAVA_MODULE: jdk/21
  DEFAULT_UV_MODULE: uv

  # Software defaults
  BZIP2: /usr/bin/bzip2
  GAWK: /usr/bin/gawk
  GZIP: /usr/bin/gzip
  XARGS: /usr/bin/xargs

includes:
  amber: ./AMBER.yml
  bactopia: ./Bactopia.yml
  bbtools: ./BBTools.yml
  bedtools: ./bedtools.yml
  blast: ./BLAST.yml
  bowtie2: ./Bowtie2.yml
  bracken: ./Bracken.yml
  bwa: ./BWA.yml
  bwa-mem2: ./BWA-MEM2.yml
  clonalframeml: ./ClonalFrameML.yml
  contig_info: ./contig_info.yml
  csvkit: ./csvkit.yml
  dbt: ./dbt-DuckDB.yml
  dsrc: ./DSRC.yml
  duckdb: ./DuckDB.yml
  falco: ./falco.yml
  fasta2agp: ./FASTA2AGP.yml
  figtree: ./FigTree.yml
  gh: ./GitHubCLI.yml
  hyperfine: ./hyperfine.yml
  jq: ./jq.yml
  kraken2: ./Kraken2.yml
  megahit: ./MEGAHIT.yml
  micromamba: ./Micromamba.yml
  minimap2: ./minimap2.yml
  miniprot: ./miniprot.yml
  mmseqs2: ./MMseqs2.yml
  ncbi-datasets: ./NCBIDatasetsCLI.yml
  ncurses: ./Ncurses.yml
  nextflow: ./Nextflow.yml
  plass-penguin: ./Plass-PenguiN.yml
  prodigal: ./Prodigal.yml
  prokka: ./Prokka.yml
  python: ./Python.yml
  quast: ./QUAST.yml
  r: ./R.yml
  raxml-ng: ./RAxML-NG.yml
  renv: ./renv.yml
  rig: ./rig.yml
  rust: ./Rust.yml
  samtools-legacy: ./SAMtools-legacy.yml
  samtools-bcftools-htslib: ./SAMtools-bcftools-htslib.yml
  seqkit: ./SeqKit.yml
  seqtk: ./Seqtk.yml
  skani: ./skani.yml
  snakemake: ./Snakemake.yml
  snpsites: ./SNPsites.yml
  srst2: ./SRST2.yml
  taskfile: ./Task.yml
  taxpasta: ./taxpasta.yml
  tinytex: ./TinyTex.yml
  treemmer: ./Treemmer.yml
  uv: ./uv.yml
  vcflib: ./vcflib.yml
  vg: ./vg.yml
  vcf2parquet: ./vcf2parquet.yml
  yq: ./yq.yml

tasks:
  default:
    - task: core

  all:
    - task: amber
    - task: bactopia
    - task: bbtools
    - task: bedtools
    - task: blast
    - task: bowtie2
    - task: bracken
    - task: bwa
    - task: bwa-mem2
    - task: clonalframeml
    - task: contig_info
    - task: csvkit
    - task: dbt
    - task: dsrc
    - task: duckdb
    - task: falco
    - task: fasta2agp
    - task: figtree
    - task: gh
    - task: hyperfine
    - task: jq
    - task: kraken2
    - task: megahit
    - task: micromamba
    - task: minimap2
    - task: miniprot
    - task: mmseqs2
    - task: ncbi-datasets
    - task: ncurses
    - task: nextflow
    - task: plass-penguin
    - task: prodigal
    - task: prokka
    - task: python
    - task: quast
    - task: r
    - task: raxml-ng
    - task: renv
    - task: rig
    - task: rust
    - task: samtools-legacy
    - task: samtools-bcftools-htslib
    - task: seqkit
    - task: seqtk
    - task: skani
    - task: snakemake
    - task: snpsites
    - task: srst2
    - task: taskfile
    - task: taxpasta
    - task: tinytex
    - task: treemmer
    - task: uv
    - task: vcf2parquet
    - task: vcflib
    - task: vg
    - task: yq

  core:
    - task: bedtools
    - task: blast
    - task: bowtie2
    - task: bracken
    - task: csvkit
    - task: duckdb
    - task: jq
    - task: kraken2
    - task: micromamba
    - task: ncbi-datasets
    - task: ncurses
    - task: nextflow
    - task: python
    - task: raxml-ng
    - task: rust
    - task: samtools-legacy
    - task: samtools-bcftools-htslib
    - task: snakemake
    - task: snpsites
    - task: srst2
    - task: taskfile
    - task: tinytex
    - task: uv
    - task: vcf2parquet
    - task: yq

  # ~*~

  amber:
    - task: amber:install
      vars:
        PYTHON: '{{.PYTHON | default .DEFAULT_PYTHON}}'
        UV_MODULE: '{{.UV_MODULE | default .DEFAULT_UV_MODULE}}'
        VERSION: '{{.VERSION | default "1.0.0"}}'

  bactopia:
    - task: bactopia:install
      vars:
        VERSION: '{{.VERSION | default "3.1.0"}}'

  bbtools:
    - task: bbtools:install
      vars:
        VERSION: '{{.VERSION | default "39.10"}}'

  bedtools:
    - task: bedtools:install
      vars:
        HTSLIB_VERSION: '{{.HTSLIB_VERSION | default "1.20"}}'
        PYTHON_VERSION: '{{.PYTHON_VERSION | default "3.12.4"}}'
        VERSION: '{{.VERSION | default "2.31.1"}}'

  blast:
    - task: blast:install
      vars:
        VERSION: '{{.VERSION | default "2.16.0"}}'

  bowtie2:
    - task: bowtie2:install
      vars:
        VERSION: '{{.VERSION | default "2.1.0"}}'

  bracken:
    - task: bracken:install
      vars:
        VERSION: '{{.VERSION | default "2.9"}}'
        KRAKEN2_VERSION: '{{.KRAKEN2_VERSION | default "2.1.3"}}'

  bwa:
    - task: bwa:install
      vars:
        VERSION: '{{.VERSION | default "0.7.18"}}'

  bwa-mem2:
    - task: bwa-mem2:install
      vars:
        VERSION: '{{.VERSION | default "2.2.1"}}'

  clonalframeml:
    - task: clonalframeml:install
      vars:
        VERSION: '{{.VERSION | default "1.13"}}'

  contig_info:
    - task: contig_info:install
      vars:
        VERSION: '{{.VERSION | default "2.01"}}'

  csvkit:
    - task: csvkit:install
      vars:
        PYTHON_VERSION: '{{.PYTHON_VERSION | default "3.12.4"}}'
        UV_VERSION: '{{.UV_VERSION | default "0.4.26"}}'
        VERSION: '{{.VERSION | default "2.0.1"}}'

  dbt:
    - task: dbt:install
      vars:
        PYTHON: '{{.PYTHON | default .DEFAULT_PYTHON}}'
        UV_MODULE: '{{.UV_MODULE | default .DEFAULT_UV_MODULE}}'
        VERSION: '{{.VERSION | default "1.8.1"}}'

  dsrc:
    - task: dsrc:install
      vars:
        VERSION: '{{.VERSION | default "2.0.2"}}'

  duckdb:
    - task: duckdb:install
      vars:
        VERSION: '{{.VERSION | default "1.1.2"}}'
    - task: duckdb:install-nightly

  falco:
    - task: falco:install
      vars:
        VERSION: '{{.VERSION | default "1.2.5"}}'

  fasta2agp:
    - task: fasta2agp:install
      vars:
        VERSION: '{{.VERSION | default "2.0"}}'

  figtree:
    - task: figtree:install
      vars:
        VERSION: '{{.VERSION | default "1.4.5_pre"}}'

  gh:
    - task: gh:install
      vars:
        VERSION: '{{.VERSION | default "2.61.0"}}'

  hyperfine:
    - task: hyperfine:install
      vars:
        VERSION: '{{.VERSION | default "1.19.0"}}'

  jq:
    - task: jq:install
      vars:
        VERSION: '{{.VERSION | default "1.7.1"}}'

  kraken2:
    - task: kraken2:install
      vars:
        VERSION: '{{.VERSION | default "2.1.3"}}'

  megahit:
    - task: megahit:install
      vars:
        VERSION: '{{.VERSION | default "1.2.9"}}'

  micromamba:
    - task: micromamba:install
      vars:
        VERSION: '{{.VERSION | default "2.0.1-0"}}'

  minimap2:
    - task: minimap2:install
      vars:
        VERSION: '{{.VERSION | default "2.28"}}'

  miniprot:
    - task: miniprot:install
      vars:
        VERSION: '{{.VERSION | default "0.13"}}'

  mmseqs2:
    - task: mmseqs2:install
      vars:
        VERSION: '{{.VERSION | default "15-6f452"}}'

  ncbi-datasets:
    - task: ncbi-datasets:install
      vars:
        VERSION_CLI: '{{.VERSION_CLI | default "16.29.0"}}'
        VERSION_DOCS: '{{.VERSION_DOCS | default "16.30.0"}}'

  ncurses:
    - task: ncurses:install
      vars:
        VERSION: '{{.VERSION | default "6.5"}}'

  nextflow:
    - task: nextflow:install
      vars:
        VERSION: '{{.VERSION | default "24.04.4"}}'

  plass-penguin:
    - task: plass-penguin:install
      vars:
        VERSION: '{{.VERSION | default "5-cf8933"}}'

  prodigal:
    - task: prodigal:install
      vars:
        VERSION: '{{.VERSION | default "2.6.3"}}'

  prokka:
    - task: prokka:install
      vars:
        VERSION: '{{.VERSION | default "1.14.6"}}'

  python:
    desc: Install Python
    summary: |
      Notes:
        - `pip` for Python2 is no longer supported.
    vars:
      VERSION: '{{.VERSION | default "3.12.4 2.7.5"}}'
      VERSIONS: '{{.VERSIONS | default .VERSION}}'
    cmds:
      - for: { var: VERSIONS }
        task: python:install
        vars:
          VERSION: '{{.ITEM}}'

  quast:
    - task: quast:install
      vars:
        VERSION: '{{.VERSION | default "5.2.0"}}'

  r:
    - task: r:install
      vars:
        VERSION: '{{.VERSION | default "4.4.2"}}'

  raxml-ng:
    - task: raxml-ng:install
      vars:
        VERSION: '{{.VERSION | default "1.2.2"}}'

  renv:
    - task: renv:install
      vars:
        VERSION: '{{.VERSION | default "1.0.11"}}'

  rig:
    - task: rig:install
      vars:
        VERSION: '{{.VERSION | default "0.7.0"}}'

  rust:
    - task: rust:install
      vars:
        VERSION: '{{.VERSION | default "1.82.0"}}'

  samtools-bcftools-htslib:
    - task: samtools-bcftools-htslib:install
      vars:
        VERSION: '{{.VERSION | default "1.20"}}'

  samtools-legacy:
    - task: samtools-legacy:install
      vars:
        NCURSES_VERSION: '{{.NCURSES_VERSION | default "6.5"}}'
        VERSION: '{{.VERSION | default "0.1.18"}}'

  seqkit:
    - task: seqkit:install
      vars:
        VERSION: '{{.VERSION | default "2.9.0"}}'

  seqtk:
    - task: seqtk:install
      vars:
        VERSION: '{{.VERSION | default "1.4"}}'

  skani:
    - task: skani:install
      vars:
        VERSION: '{{.VERSION | default "0.2.2"}}'

  snakemake:
    - task: snakemake:install
      vars:
        MICROMAMBA_VERSION: '{{.MICROMAMBA_VERSION | default "2.0.1-0"}}'
        VERSION: '{{.VERSION | default "8.16"}}'

  snpsites:
    - task: snpsites:install
      vars:
        VERSION: '{{.VERSION | default "2.5.1"}}'

  srst2:
    - task: srst2:install
      vars:
        BOWTIE2_VERSION: '{{.BOWTIE2_VERSION | default "2.1.0"}}'
        SAMTOOLS_VERSION: '{{.SAMTOOLS_VERSION | default "0.1.18"}}'
        VERSION: '{{.VERSION | default "0.2.0"}}'

  taskfile:
    - task: taskfile:install
      vars:
        VERSION: '{{.VERSION | default "3.39.2"}}'

  taxpasta:
    - task: taxpasta:install
      vars:
        VERSION: '{{.VERSION | default "0.7.0"}}'

  tinytex:
    - task: tinytex:install
      vars:
        VERSION: '{{.VERSION | default "2024.07.03"}}'

  treemmer:
    - task: treemmer:install
      vars:
        VERSION: '{{.VERSION | default "0.3"}}'

  uv:
    - task: uv:install
      vars:
        RUST_VERSION: '{{.RUST_VERSION | default "1.82.0"}}'
        VERSION: '{{.VERSION | default "0.4.26"}}'

  vcf2parquet:
    - task: vcf2parquet:install
      vars:
        MICROMAMBA_VERSION: '{{.MICROMAMBA_VERSION | default "2.0.1-0"}}'
        VERSION: '{{.VERSION | default "0.4.1"}}'

  vcflib:
    - task: vcflib:install
      vars:
        VERSION: '{{.VERSION | default "1.0.10"}}'

  vg:
    - task: vg:install
      vars:
        VERSION: '{{.VERSION | default "1.60.0"}}'

  yq:
    - task: yq:install
      vars:
        VERSION: '{{.VERSION | default "4.44.3"}}'