version: '3'

vars:
  HOME: $HOME
  DIR: '{{ .DIR | default .HOME }}'

tasks:
  finish:
    - task: symlink
    - task: modulefile
  
  symlink:
    silent: True
    dir: $GROUP_HOME/bin
    cmds:
      - for: { var: EXE, as: GROUP_EXE }
        cmd: echo "ln -s ../opt/{{.SUBDIR}}/{{.RELPATH_EXE}}{{.GROUP_EXE}} {{.GROUP_EXE}}"
    generates:
      - $GROUP_HOME/bin/{{.EXE}}
    requires:
      vars: [SUBDIR, RELPATH_EXE, EXE]

  modulefile:
    dir: $GROUP_HOME/Modules/modulefiles/{{.APP}}
    cmds:
      - |
        echo "writing modulefile"
    generates:
      - $GROUP_HOME/Modules/modulefiles/{{.APP}}/{{.VERSION}}
    requires:
      vars: [APP, VERSION]

  check_software:
    silent: True
    cmds:
      - command -v {{.SOFTWARE}} >/dev/null 2>&1 || exit 1
    requires:
      vars: [SOFTWARE]

  cleanup:
    silent: True
    dir: $GROUP_HOME/opt/{{.SUBDIR}}
    cmds:
      - rm -f $(basename ${{.BINARY}})
    requires:
      vars: [SUBDIR, BINARY]