version: '3'

includes:
  envs: ./tasks/envs/EnvsTasks.yml
  install: ./tasks/InstallTasks.yml
  download: ./tasks/PublicDataTasks.yml

tasks:
  setup:
    prompt: Are you setting up a new HPC?
    cmds:
      - task: install:core
      - task: download:all