version: '3'

# Usage: ~/bin/task --concurrency 1 --yes

vars:
  GROUP_HOME:
    sh: echo $GROUP_HOME
  SHELL:
    sh: echo $SHELL
  BASHRC: ~/.bashrc

dotenv: ['{{.TASKFILE_DIR}}/.env', '{{.HOME}}/.env']

includes:
  public-data: ./setup-tasks/data
  envs: ./setup-tasks/envs
  install: ./setup-tasks/software

# TODO: Download local versions of nf-core pipelines
# TODO: Back up srst2 database somewhere (?) and copy over to viper
# TODO: Add PubMLST
# TODO: Add non-standalone nextflow + nf-core utils in conda env

tasks:
  default:
    prompt: Are you setting up a new HPC?
    cmds:
      - task: furnish-group-home
      - task: install
      - task: envs
      - task: public-data

  furnish-group-home:
    desc: Group home directory structure
    vars:
      GROUP_HOME_DIRS: |
        bin config containers envs fonts lab_data Modules/modulefiles 
        opt public_data tmp tools
    dir: '{{.GROUP_HOME}}'
    prompt: Is {{.GROUP_HOME}} correct?
    cmds:
      - mkdir -p {{.GROUP_HOME_DIRS}}
    # Check that group home exists. Its creation should be managed by HPC admins.
    preconditions:
      - test -d "{{.GROUP_HOME}}"
    requires:
      vars: [GROUP_HOME]
    status:
      - test -d {{.GROUP_HOME}}/opt
      - test -d {{.GROUP_HOME}}/Modules/modulefiles