version: '3'

vars:
  GROUP_HOME:
    sh: echo $GROUP_HOME
  SHELL:
    sh: echo $SHELL
  BASHRC: ~/.bashrc

dotenv: ['{{.TASKFILE_DIR}}/.env', '{{.HOME}}/.env']

includes:
  public-data: ./setup-tasks/data
  envs: ./setup-tasks/envs
  install: ./setup-tasks/software

# TODO: Write Taskfile or Makefile for setting up remotes (directory creation, rclone, etc.)
# TODO: Re-define "install:core" based on WideVariant and download:all
#       - nextflow
# TODO: Create containers
# TODO: Download local versions of nf-core pipelines
# TODO: Back up srst2 database somewhere (?) and copy over to viper
# TODO: Add PubMLST

tasks:
  default:
    prompt: Are you setting up a new HPC?
    cmds:
      - task: furnish-group-home
      - task: minimal-tmp-shell-profile
      - task: install
      - task: envs
      - task: public-data

  furnish-group-home:
    desc: Group home directory structure
    vars:
      GROUP_HOME_DIRS: opt Modules/modulefiles
    dir: '{{.GROUP_HOME}}'
    prompt: Is {{.GROUP_HOME}} correct?
    cmds:
      - mkdir -p {{.GROUP_HOME_DIRS}}
    # Check that group home exists. Its creation should be managed by HPC admins.
    preconditions:
      - test -d "{{.GROUP_HOME}}"
    requires:
      vars: [GROUP_HOME]
    status:
      - test -d {{.GROUP_HOME}}/opt
      - test -d {{.GROUP_HOME}}/Modules/modulefiles

  minimal-tmp-shell-profile:
    desc: Create minimal profile
    cmds:
      - echo -e '\n\nexport GROUP_HOME="{{.GROUP_HOME}}"' >> {{.BASHRC}}
      - echo -e 'export MODULE_BASEDIR="$GROUP_HOME/opt"' >> {{.BASHRC}}
      - echo -e '\nmodule use --append "$GROUP_HOME/Modules/modulefiles"' >> {{.BASHRC}}
      - '{{.SHELL}} -c "exec {{.SHELL}}"'