version: '3'

vars:
  APPTAINER: apptainer/1.3.2
  UBUNTU_VERSION: 20.04

tasks:
  aria2:
    dir: $GROUP_HOME
    deps: [ubuntu]
    cmds:
      - bash -c 'module purge
        module load {{.APPTAINER}}
        apptainer build \
            --bind "/ptmp/thosi/apptainer-build:/tmp" \
            --notest \
            --build-arg ARIA2_VERSION={{.VERSION}} UBUNTU_VERSION={{.UBUNTU_VERSION}} \
            ./containers/aria2.sif \
            ./tools/keylab-apptainer-definitions/utils/aria2c.def'
    vars:
      VERSION: 1.37.0
    requires:
      vars: [APPTAINER, UBUNTU_VERSION]
    status:
      - test -f $GROUP_HOME/containers/aria2c.sif

  ubuntu:
    dir: $GROUP_HOME
    cmds:
      - bash -c 'module purge
        module load {{.APPTAINER}}
        apptainer build \
            --bind "/ptmp/thosi/apptainer-build:/tmp" \
            --notest \
            --build-arg VERSION={{.UBUNTU_VERSION}} \
            ./containers/ubuntu{{.UBUNTU_VERSION}}.sif \
            ./tools/keylab-apptainer-definitions/base/ubuntu.def'
    requires:
      vars: [APPTAINER, UBUNTU_VERSION]
    status:
      - test -f $GROUP_HOME/containers/ubuntu{{.UBUNTU_VERSION}}.sif