version: '3'

includes:
  fasttree: ./software/FastTree.yml
  gubbins: ./software/Gubbins.yml
  tinytex: ./software/TinyTex.yml

tasks:
  all:
    - task: fasttree
    - task: gubbins
    - task: tinytex

  core:
    - task: gubbins

  bio:
    - task: fasttree
    - task: gubbins

  utils:
    - task: tinytex

  fasttree:
    - task: fasttree:install
    - task: fasttree:install_dbl
    - task: fasttree:install_openmp

  gubbins:
    - task: gubbins:install

  tinytex:
    - task: tinytex:install