version: '3'

includes:
  aria2: ./software/Aria2.yml
  bowtie2: ./software/Bowtie2.yml
  duckdb: ./software/DuckDB.yml
  fasttree: ./software/FastTree.yml
  gubbins: ./software/Gubbins.yml
  ncurses: ./software/Ncurses.yml
  pandoc: ./software/Pandoc.yml
  python: ./software/Python.yml
  rust: ./software/Rust.yml
  samtools: ./software/SAMtools.yml
  snpsites: ./software/SNPsites.yml
  srst2: ./software/SRST2.yml
  tinytex: ./software/TinyTex.yml
  veryfasttree: ./software/VeryFastTree.yml
  yq: ./software/yq.yml

vars:
  CA_BUNDLE: /etc/ssl/ca-bundle.pem

tasks:
  default: core
  
  all:
    - task: aria2
    - task: bowtie2
    - task: duckdb
    - task: fasttree
    - task: gubbins
    - task: ncurses
    - task: pandoc
    - task: python
    - task: rust
    - task: samtools
    - task: snpsites
    - task: srst2
    - task: tinytex
    - task: veryfasttree
    - task: yq

  # ~*~

  core:
    - task: bowtie2
    - task: gubbins
    - task: python
    - task: snpsites
    - task: srst2

  bio:
    - task: bowtie2
    - task: fasttree
    - task: gubbins
    - task: samtools
    - task: snpsites
    - task: srst2
    - task: veryfasttree

  data:
    - task: duckdb
    - task: yq

  utils:
    - task: aria2
    - task: ncurses
    - task: pandoc
    - task: tinytex

  interpreters:
    - task: python

  compilers:
    - task: rust

  # ~*~

  aria2:
    - task: aria2:install

  bowtie2:
    - task: bowtie2:install

  duckdb:
    - task: duckdb:install
    - task: duckdb:install_nightly

  fasttree:
    - task: fasttree:install
    - task: fasttree:install_dbl
    - task: fasttree:install_openmp

  gubbins:
    - task: gubbins:install

  ncurses:
    - task: ncurses:install

  pandoc:
    - task: pandoc:install

  python:
    - task: python:install_3_12
    - task: python:install_2_7

  samtools:
    - task: samtools:install

  rust:
    - task: rust:install

  snpsites:
    - task: snpsites:install

  srst2:
    - task: srst2:install

  tinytex:
    - task: tinytex:install

  veryfasttree:
    - task: veryfasttree:install_py

  yq:
    - task: yq:install