version: '3'

includes:
  aria2: ./software/Aria2.yml
  ariba: ./software/ARIBA.yml
  bedtools: ./software/bedtools.yml
  blast: ./software/BLAST.yml
  bowtie2: ./software/Bowtie2.yml
  cdhit: ./software/CD-HIT.yml
  d4tools: ./software/D4.yml
  direnv: ./software/direnv.yml
  duckdb: ./software/DuckDB.yml
  fasttree: ./software/FastTree.yml
  gatk: ./software/GATK.yml
  gnumeric: ./software/Gnumeric.yml
  gubbins: ./software/Gubbins.yml
  jq: ./software/jq.yml
  kma: ./software/KMA.yml
  kmerresistance: ./software/KmerResistance.yml
  mosdepth: ./software/mosdepth.yml
  mummer: ./software/MUMmer.yml
  ncbi_datasets: ./software/NCBIDatasetsCLI.yml
  ncurses: ./software/Ncurses.yml
  nim: ./software/Nim.yml
  pandoc: ./software/Pandoc.yml
  perl: ./software/Perl.yml
  python: ./software/Python.yml
  resfinder: ./software/ResFinder.yml
  rust: ./software/Rust.yml
  samtools: ./software/SAMtools.yml
  samtools_bcftools_htslib: ./software/SAMtools-bcftools-htslib.yml
  snpsites: ./software/SNPsites.yml
  spades: ./software/SPAdes.yml
  srst2: ./software/SRST2.yml
  tinytex: ./software/TinyTex.yml
  vcftools: ./software/VCFtools.yml
  veryfasttree: ./software/VeryFastTree.yml
  yadm: ./software/yadm.yml
  yq: ./software/yq.yml

vars:
  CA_BUNDLE: /etc/ssl/ca-bundle.pem

tasks:
  default: core
  
  all:
    - task: aria2
    - task: ariba
    - task: bedtools
    - task: blast
    - task: bowtie2
    - task: cdhit
    - task: d4tools
    - task: direnv
    - task: duckdb
    - task: fasttree
    - task: gatk
    - task: gnumeric
    - task: gubbins
    - task: jq
    - task: kma
    - task: kmerresistance
    - task: mosdepth
    - task: mummer
    - task: ncbi_datasets
    - task: ncurses
    - task: nim
    - task: pandoc
    - task: perl
    - task: python
    - task: resfinder
    - task: rust
    - task: samtools
    - task: samtools_bcftools_htslib
    - task: snpsites
    - task: spades
    - task: srst2
    - task: tinytex
    - task: vcftools
    - task: veryfasttree
    - task: yadm
    - task: yq

  # ~*~

  core:
    - task: bedtools
    - task: blast
    - task: bowtie2
    - task: gatk
    - task: gubbins
    - task: ncbi_datasets
    - task: python
    - task: samtools
    - task: samtools_bcftools_htslib
    - task: snpsites
    - task: srst2
    - task: vcftools

  bio:
    - task: ariba
    - task: bedtools
    - task: blast
    - task: bowtie2
    - task: d4tools
    - task: cdhit
    - task: fasttree
    - task: gatk
    - task: gubbins
    - task: kma
    - task: kmerresistance
    - task: mosdepth
    - task: mummer
    - task: ncbi_datasets
    - task: resfinder
    - task: samtools
    - task: samtools_bcftools_htslib
    - task: snpsites
    - task: spades
    - task: srst2
    - task: veryfasttree
    - task: vcftools

  admin:
    - task: yadm

  data:
    - task: d4tools
    - task: duckdb
    - task: gnumeric
    - task: jq
    - task: yq

  utils:
    - task: aria2
    - task: direnv
    - task: ncurses
    - task: pandoc
    - task: tinytex

  interpreters:
    - task: perl
    - task: python

  compilers:
    - task: nim
    - task: rust

  # ~*~

  aria2:
    - task: aria2:install

  ariba:
    - task: ariba:install

  bedtools:
    - task: bedtools:install

  blast:
    - task: blast:install

  bowtie2:
    - task: bowtie2:install

  cdhit:
    - task: cdhit:install

  d4tools:
    - task: d4tools:install

  direnv:
    - task: direnv:install

  duckdb:
    - task: duckdb:install
    - task: duckdb:install_nightly

  fasttree:
    - task: fasttree:install
    - task: fasttree:install_dbl
    - task: fasttree:install_openmp

  gatk:
    - task: gatk:install

  gnumeric:
    - task: gnumeric:install

  gubbins:
    - task: gubbins:install

  jq:
    - task: jq:install

  kma:
    - task: kma:install

  kmerresistance:
    - task: kmerresistance:install

  mosdepth:
    - task: mosdepth:install

  mummer:
    - task: mummer:install

  ncbi_datasets:
    - task: ncbi_datasets:install

  ncurses:
    - task: ncurses:install

  nim:
    - task: nim:install

  pandoc:
    - task: pandoc:install

  perl:
    - task: perl:install

  python:
    - task: python:install_3_12
    - task: python:install_2_7

  samtools:
    - task: samtools:install

  snpsites:
    - task: snpsites:install
  
  spades:
    - task: spades:install

  srst2:
    - task: srst2:install

  resfinder:
    - task: resfinder:install

  rust:
    - task: rust:install

  samtools:
    - task: samtools:install

  samtools_bcftools_htslib:
    - task: samtools_bcftools_htslib:install

  snpsites:
    - task: snpsites:install

  srst2:
    - task: srst2:install

  tinytex:
    - task: tinytex:install

  vcftools:
    - task: vcftools:install

  veryfasttree:
    - task: veryfasttree:install_py

  yadm:
    - task: yadm:install

  yq:
    - task: yq:install