version: '3'

includes:
  aria2: ./software/Aria2.yml
  ariba: ./software/ARIBA.yml
  blast: ./software/BLAST.yml
  bowtie2: ./software/Bowtie2.yml
  cdhit: ./software/CD-HIT.yml
  duckdb: ./software/DuckDB.yml
  fasttree: ./software/FastTree.yml
  gnumeric: ./software/Gnumeric.yml
  gubbins: ./software/Gubbins.yml
  kma: ./software/KMA.yml
  kmerresistance: ./software/KmerResistance.yml
  mummer: ./software/MUMmer.yml
  ncurses: ./software/Ncurses.yml
  pandoc: ./software/Pandoc.yml
  perl: ./software/Perl.yml
  python: ./software/Python.yml
  resfinder: ./software/ResFinder.yml
  rust: ./software/Rust.yml
  samtools: ./software/SAMtools.yml
  snpsites: ./software/SNPsites.yml
  spades: ./software/SPAdes.yml
  srst2: ./software/SRST2.yml
  tinytex: ./software/TinyTex.yml
  veryfasttree: ./software/VeryFastTree.yml
  yq: ./software/yq.yml

vars:
  CA_BUNDLE: /etc/ssl/ca-bundle.pem

tasks:
  default: core
  
  all:
    - task: aria2
    - task: ariba
    - task: blast
    - task: bowtie2
    - task: cdhit
    - task: duckdb
    - task: fasttree
    - task: gnumeric
    - task: gubbins
    - task: kma
    - task: kmerresistance
    - task: mummer
    - task: ncurses
    - task: pandoc
    - task: perl
    - task: python
    - task: resfinder
    - task: rust
    - task: samtools
    - task: snpsites
    - task: spades
    - task: srst2
    - task: tinytex
    - task: veryfasttree
    - task: yq

  # ~*~

  core:
    - task: blast
    - task: bowtie2
    - task: gubbins
    - task: python
    - task: snpsites
    - task: srst2

  bio:
    - task: ariba
    - task: blast
    - task: bowtie2
    - task: cdhit
    - task: fasttree
    - task: gubbins
    - task: kma
    - task: kmerresistance
    - task: mummer
    - task: resfinder
    - task: samtools
    - task: snpsites
    - task: spades
    - task: srst2
    - task: veryfasttree

  data:
    - task: duckdb
    - task: gnumeric
    - task: yq

  utils:
    - task: aria2
    - task: ncurses
    - task: pandoc
    - task: tinytex

  interpreters:
    - task: perl
    - task: python

  compilers:
    - task: rust

  # ~*~

  aria2:
    - task: aria2:install

  ariba:
    - task: ariba:install

  blast:
    - task: blast:install

  bowtie2:
    - task: bowtie2:install

  cdhit:
    - task: cdhit:install

  duckdb:
    - task: duckdb:install
    - task: duckdb:install_nightly

  fasttree:
    - task: fasttree:install
    - task: fasttree:install_dbl
    - task: fasttree:install_openmp

  gnumeric:
    - task: gnumeric:install

  gubbins:
    - task: gubbins:install

  kma:
    - task: kma:install

  kmerresistance:
    - task: kmerresistance:install

  mummer:
    - task: mummer:install

  ncurses:
    - task: ncurses:install

  pandoc:
    - task: pandoc:install

  perl:
    - task: perl:install

  python:
    - task: python:install_3_12
    - task: python:install_2_7

  samtools:
    - task: samtools:install

  snpsites:
    - task: snpsites:install
  
  spades:
    - task: spades:install

  srst2:
    - task: srst2:install

  resfinder:
    - task: resfinder:install

  rust:
    - task: rust:install

  snpsites:
    - task: snpsites:install

  srst2:
    - task: srst2:install

  tinytex:
    - task: tinytex:install

  veryfasttree:
    - task: veryfasttree:install_py

  yq:
    - task: yq:install