version: 3

includes:
  igenomes: ./data/iGenomes.yml
  kraken2: ./data/Kraken2Database.yml
  ncbi_reference: ./data/NCBIReference.yml
  ncbi_taxonomy: ./data/NCBITaxonomy.yml
  pubmlst: ./data/PubMLST.yml

tasks:
  all:
    - task: igenome-reference-genomes
    - task: ncbi-reference-genomes
    - task: ncbi-taxranks
    - task: kraken2-db
    - task: pubmlst
  
  igenome-reference-genomes:
    - task: igenomes:download_ecoli
  
  ncbi-reference-genomes:
    - task: ncbi_reference:download-core-reference-genomes

  ncbi-taxranks:
    - task: ncbi_taxonomy:download

  kraken2-db:
    - task: kraken2:download-ccbjhu
    - task: kraken2:download-other-dbs
  
  pubmlst:
    - task: pubmlst:ariba_db