version: 3

includes:
  igenomes: ./data/iGenomes.yml
  ncbi_taxonomy: ./data/NCBITaxonomy.yml
  pubmlst: ./data/PubMLST.yml

tasks:
  all:
    - task: ncbi_taxranks
    - task: pubmlst
    - task: reference_genomes

  ncbi_taxranks:
    - task: ncbi_taxonomy:download
  
  pubmlst:
    - task: pubmlst:ariba_db
  
  reference_genomes:
    - task: igenomes:download_ecoli