version: '3'

vars:
  GROUP_VENVS: '{{.GROUP_HOME}}/envs/venv'
  UV: '{{.OPT_DIR}}/uv/0.2.34/bin/uv'

includes:
  utils: ../../lab-tasks
  install: ../software

  # uv envs
  data-pipeline: ./DataPipeline.yml
  python-packaging: ./PythonPackaging.yml
  sandbox: ./Sandbox.yml

tasks:
  default:
    - task: create-python-envs-uv
    - task: create-python-envs-mamba

  create-python-envs-uv:
    deps:
      - task: install:python
      - task: install:uv
    cmds:
      - task: data-pipeline:create
      - task: python-packaging:create
      - task: sandbox:create
  
  create-python-envs-mamba:
    deps:
      - task: install:micromamba
