version: '3'

includes:
  group_install: ../utils/GroupInstallTasks.yml

tasks:
  install:
    desc: Install DuckDB
    cmds:
      - task: _install
        vars:
          VERSION: 1.0.0
          BINARY: https://github.com/duckdb/duckdb/releases/download/v1.0.0/duckdb_cli-linux-amd64.zip

  install_nightly:
    desc: Install DuckDB (nightly)
    cmds:
      - task: _install
        vars:
          VERSION: nightly
          BINARY: https://artifacts.duckdb.org/latest/duckdb-binaries-linux.zip

  _install:
    internal: true
    vars:
      APP: duckdb
      RELPATH_EXE: /
    deps:
      - task: build
        vars:
          BINARY: '{{.BINARY}}'
          SUBDIR: '{{.APP}}/{{.VERSION}}'
    cmds:
      - task: group_install:complete
        vars:
          APP: '{{.APP}}'
          VERSION: '{{.VERSION}}'
          RELPATH_EXE: '{{.RELPATH_EXE}}'
          EXE: '{{.APP}}'

  build:
    dir: $GROUP_HOME/opt/{{.SUBDIR}}
    summary: |
      Download DuckDB zipped binaries.

      Notes:
        - The nightly build comes with two zips
    cmds:
      - wget {{.BINARY}}
      - defer: rm -f *.zip
      - unzip *.zip
    status:
      - test -f $GROUP_HOME/opt/{{.SUBDIR}}/duckdb