version: '3'

includes:
  group_install: ../utils/GroupInstallTasks.yml

# TODO: Install extensions: 
#   `install spatial;` for stable (works)
#   `install spatial from core_nightly;` for nightly (fails)

tasks:
  install_nightly:
    desc: Install DuckDB (nightly)
    cmds:
      - task: install
        vars:
          VERSION: nightly
          URL: '{{.URL_NIGHTLY}}'
    vars:
      URL_NIGHTLY: https://artifacts.duckdb.org/latest/duckdb-binaries-linux.zip

  install:
    desc: Install DuckDB
    cmds:
      - task: download
        vars:
          URL: '{{.URL}}'
          VERSION: '{{.VERSION}}'
      - task: group_install:complete
        vars:
          APP: '{{.APP}}'
          VERSION: '{{.VERSION}}'
          RELPATH_EXE: /
          EXE: '{{.APP}}'
    vars:
      APP: duckdb
      VERSION: '{{.VERSION | default "1.0.0"}}'
      URL_STABLE: https://github.com/duckdb/duckdb/releases/download/v{{.VERSION}}/duckdb_cli-linux-amd64.zip
      URL: '{{.URL | default .URL_STABLE}}'

  download:
    dir: '{{.DIR}}'
    prompt: Download to {{.DIR}}?
    summary: |
      Download DuckDB zipped pre-compiled binaries.

      Notes
      -----
        - The nightly build comes with two zips
    cmds:
      - wget {{.URL}}
      - defer: rm -f *.zip
      - unzip *.zip
    vars:
      DIR: $GROUP_HOME/opt/duckdb/{{.VERSION}}
    requires:
      vars: [URL, VERSION]
    status:
      - test -f {{.DIR}}/duckdb