version: '3'

includes:
  group_install: ../utils/GroupInstallTasks.yml

tasks:
  install:
    desc: Install jq
    summary: |
      Install jq

      Notes
      -----
      - Message upon successful install:
      
      ```bash
      ----------------------------------------------------------------------
      Libraries have been installed in:
        $GROUP_HOME/opt/jq/1.7.1/lib

      If you ever happen to want to link against installed libraries
      in a given directory, LIBDIR, you must either use libtool, and
      specify the full pathname of the library, or use the '-LLIBDIR'
      flag during linking and do at least one of the following:
        - add LIBDIR to the 'LD_LIBRARY_PATH' environment variable
          during execution
        - add LIBDIR to the 'LD_RUN_PATH' environment variable
          during linking
        - use the '-Wl,-rpath -Wl,LIBDIR' linker flag
        - have your system administrator add LIBDIR to '/etc/ld.so.conf'

      See any operating system documentation about shared libraries for
      more information, such as the ld(1) and ld.so(8) manual pages.
      ----------------------------------------------------------------------
      ```

      URLs
      ----
      - https://jqlang.github.io/jq
    cmds:
      - task: group_install:build-from-source-vanilla
        vars:
          APP: '{{.APP}}'
          PREFIX: $GROUP_HOME/opt/{{.APP}}/{{.VERSION}}
          STATUS: '-f $GROUP_HOME/opt/{{.APP}}/{{.VERSION}}/bin/jq'
          URL: https://github.com/jqlang/jq/releases/download/jq-{{.VERSION}}/jq-{{.VERSION}}.tar.gz
          VERSION: '{{.VERSION}}'
      - task: group_install:symlink
        vars:
          EXE: '{{.APP}}'
          RELPATH_EXE: '/bin/'
          SUBDIR: '{{.APP}}/{{.VERSION}}'
    vars:
      APP: jq
      VERSION: '{{.VERSION | default "1.7.1"}}'