version: '3'

includes:
  group_install: ../utils/GroupInstallTasks.yml

tasks:
  install:
    desc: Install Perl
    summary: |
      Install Perl

      Notes
      -----
      - https://www.cpan.org/src/README.html
    cmds:
      - task: build
        vars:
          APP: '{{.APP}}'
          VERSION: '{{.VERSION}}'
      - task: group_install:complete
        vars:
          APP: '{{.APP}}'
          VERSION: '{{.VERSION}}'
          RELPATH_EXE: /bin/
          EXE: '{{.APP}}'
    vars:
      APP: perl
      VERSION: '{{.VERSION | default "5.40.0"}}'

  build:
    dir: '{{.DIR}}'
    prompt: 'Download in {{.DIR}}?'
    cmds:
      - wget {{.URL}}
      - defer: rm -f $(basename ${{.URL}})
      - tar -xzf $(basename ${{.URL}})
      - |
        cd perl-{{.VERSION}}
        ./Configure -des -Dprefix={{.DIR}}
        make; make install
    vars:
      DIR: $GROUP_HOME/opt/{{.APP}}/{{.VERSION}}
      URL: https://www.cpan.org/src/5.0/perl-{{.VERSION}}.tar.gz
    status:
      - test -f {{.DIR}}/bin/perl