version: '3'

includes:
  group_install: ../utils/GroupInstallTasks.yml

tasks:
  install:
    desc: Install Rust
    summary: |
      Note:
      # To get started you need Cargo's bin directory 
      # ($GROUP_HOME/opt/rust/1.80.1/bin) in your PATH
      # environment variable. This has not been done automatically.

      # To configure your current shell, you need to source
      # the corresponding env file under $GROUP_HOME/opt/rust/1.80.1.

      # This is usually done by running one of the following (note the leading DOT):
      # . "$GROUP_HOME/opt/rust/1.80.1/env"            # For 
      # sh/bash/zsh/ash/dash/pdksh
      # source "$GROUP_HOME/opt/rust/1.80.1/env.fish"  # For fish
    cmds:
      - task: _install
        vars:
          APP: rust
          VERSION: 1.80.1
          RELPATH_EXE: /bin/
          EXE: rustc rustup cargo

  _install:
    internal: true
    deps:
      - task: build
        vars:
          SUBDIR: '{{.APP}}/{{.VERSION}}'
    cmds:
      - task: group_install:complete
        vars:
          APP: '{{.APP}}'
          VERSION: '{{.VERSION}}'
          RELPATH_EXE: '{{.RELPATH_EXE}}'
          EXE: '{{.EXE}}'

  build:
    dir: $GROUP_HOME/opt/{{.SUBDIR}}
    cmds:
      - mkdir -p bin
      - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- --no-modify-path -y
    env:
      # Will look for a `bin` directory in these locations
      RUSTUP_HOME: $GROUP_HOME/opt/rust/1.80.1
      CARGO_HOME: $GROUP_HOME/opt/rust/1.80.1
    status:
      - test -f $GROUP_HOME/opt/{{.SUBDIR}}/bin/rustc
      - test -f $GROUP_HOME/opt/{{.SUBDIR}}/bin/cargo