version: 3

includes:
  group-install: ../utils/GroupInstallTasks.yml
  envmodules: ../../../lab-tasks/tasks/EnvironmentModules.yml
  ncurses: Ncurses.yml

tasks:
  install:
    vars:
      APP: samtools
      VERSION: '{{.VERSION | default "0.1.18"}}'
      NCURSES_MODULE: ncurses/6.5
    cmds:
      - task: build
        vars:
          NCURSES_MODULE: '{{.NCURSES_MODULE}}'
          VERSION: '{{.VERSION}}'
      # NOTE: Added /misc/ to path too
      - task: group-install:complete
        vars:
          APP: '{{.APP}}'
          VERSION: '{{.VERSION}}'
          RELPATH_EXE: /samtools-{{.VERSION}}/
          EXE: '{{.APP}}'

  build:
    deps:
      - task: ncurses:install
    vars:
      DIR: $GROUP_HOME/opt/samtools/{{.VERSION}}
      URL: https://sourceforge.net/projects/samtools/files/samtools{{.VERSION}}/samtools-{{.VERSION}}.tar.bz2
    dir: '{{.DIR}}'
    prompt: Build in {{.DIR}}?
    cmds:
      - wget {{.URL}}
      - defer: rm -f $(basename {{.URL}})
      - tar xf $(basename {{.URL}})
      - task: envmodules:run-inside
        vars:
          CMDS: |
            cd {{.DIR}}/samtools-{{.VERSION}} && 
            make LIBCURSES="-lncursesw"
          MODULE: '{{.NCURSES_MODULE}}'
    requires:
      vars: [NCURSES_MODULE, VERSION]
    status:
      - test -f $GROUP_HOME/opt/{{.SUBDIR}}/samtools-0.1.18/samtools
      - test -f $GROUP_HOME/opt/{{.SUBDIR}}/samtools-0.1.18/misc/maq2sam-long
      - test -f $GROUP_HOME/opt/{{.SUBDIR}}/samtools-0.1.18/misc/maq2sam-short
      - test -f $GROUP_HOME/opt/{{.SUBDIR}}/samtools-0.1.18/misc/md5fa
      - test -f $GROUP_HOME/opt/{{.SUBDIR}}/samtools-0.1.18/misc/md5sum-lite
      - test -f $GROUP_HOME/opt/{{.SUBDIR}}/samtools-0.1.18/misc/seqtk
      - test -f $GROUP_HOME/opt/{{.SUBDIR}}/samtools-0.1.18/misc/wgsim