version: '3'

includes:
  group_install: ../utils/GroupInstallTasks.yml

tasks:
  install:
    desc: Install TinyTex
    summary: |
      Install a Tex compiler

      Check here for latest release:
      https://github.com/rstudio/tinytex-releases
    cmds:
      - task: _install
        vars:
          APP: tinytex
          VERSION: 2024.07.03
          BINARY: https://github.com/rstudio/tinytex-releases/releases/download/v2024.07.03/TinyTeX-1-v2024.07.03.tar.gz
          RELPATH_EXE: .TinyTeX/bin/x86_64-linux/
          EXE: latexmk pdflatex bibtex tlmgr

  _install:
    deps:
      - task: build
        vars:
          BINARY: '{{.BINARY}}'
          SUBDIR: '{{.APP}}/{{.VERSION}}'
    cmds:
      - task: group_install:complete
        vars:
          APP: '{{.APP}}'
          VERSION: '{{.VERSION}}'
          RELPATH_EXE: '{{.RELPATH_EXE}}'
          EXE: '{{.EXE}}'

  build:
    dir: $GROUP_HOME/opt/{{.SUBDIR}}
    deps:
      - task: group_install:check_software
        vars:
          SOFTWARE: perl
    cmds:
      - echo 'wget {{.BINARY}}'
      - echo 'tar xf $(basename ${{.BINARY}})'
      - echo 'rm -f $(basename ${{.BINARY}})'
    status:
      - test -f $GROUP_HOME/opt/{{.SUBDIR}}/.TinyTeX/latexmk