version: '3'

includes:
  group_install: ../utils/GroupInstallTasks.yml

tasks:
  install_py:
    desc: Install VeryFastTree Python Bindings
    summary: |
      VeryFastTree

      The VeryFastTree Python Bindings provide an interface to the VeryFastTree 
      software for rapid construction of phylogenetic trees. This package 
      allows you to easily integrate VeryFastTree into your Python workflows, 
      enabling efficient handling of large datasets and quick tree generation.

      References:
      - https://github.com/citiususc/veryfasttree
      - https://pypi.org/project/veryfasttree/
    cmds:
      - task: _install
        vars:
          APP: veryfasttree
          VERSION: 4.0.3.1

  _install:
    deps:
      - task: build
        vars:
          VERSION: '{{.VERSION}}'
          SUBDIR: '{{.APP}}/{{.VERSION}}'

  build:
    dir: $GROUP_HOME/opt/{{.SUBDIR}}
    vars:
      UV_MODULE: uv/0.2.34
      PYTHON_INTERPRETER: $GROUP_HOME/opt/python/python/bin/python3.12
    deps:
      - task: group_install:check_software
        vars:
          SOFTWARE: '{{.PYTHON_INTERPRETER}}'
    cmds:
      - bash -c 'module load {{.UV_MODULE}} &&
        cd $GROUP_HOME/opt/{{.SUBDIR}} &&
        uv venv --python={{.PYTHON_INTERPRETER}} &&
        source .venv/bin/activate &&
        uv pip install veryfasttree~=4.0 &&
        deactivate &&
        module unload {{.UV_MODULE}}'
    status:
      - test -d $GROUP_HOME/opt/veryfasttree/{{.VERSION}}/.venv/lib/python3.12/site-packages/veryfasttree