version: '3'

includes:
  group_install: ../utils/GroupInstallTasks.yml

tasks:
  install:
    desc: Install yadm
    summary: |
      Install yadm

      URLs
      ----
      - https://yadm.io
    cmds:
      - task: build
        vars:
          SUBDIR: '{{.APP}}/{{.VERSION}}'
      - task: group_install:complete
        vars:
          APP: '{{.APP}}'
          VERSION: '{{.VERSION}}'
          RELPATH_EXE: '{{.RELPATH_EXE}}'
          EXE: '{{.APP}}'
    vars:
      APP: yadm
      VERSION: 3.2.2
      RELPATH_EXE: /yadm/

  build:
    dir: $GROUP_HOME/opt/{{.SUBDIR}}
    prompt: Install in $GROUP_HOME/opt/{{.SUBDIR}}? 
    cmds:
      - git clone https://github.com/TheLocehiliosan/yadm.git
    status:
      - test -f $GROUP_HOME/opt/{{.SUBDIR}}/yadm/yadm