version: '3'

tasks:
  nb_to_pdf:
    summary: |
      Doesn't work well.

      Troubleshooting:
        - first load environment used for `your_notebook.ipynb` kernel
        - the closing $ must have a non-space character immediately to its left
        - can try `jupyter nbconvert --to latex your_notebook.ipynb`
    vars:
      PANDOC_MODULE: 'pandoc/3.3'
      TEX_MODULE: 'tinytex/2024.07.03'
    cmds:
      - task: install_tex_packages
        vars:
          TEX_MODULE: '{{.TEX_MODULE}}'
      - bash -c '
      module purge; module load {{.PANDOC_MODULE}} {{.TEX_MODULE}} &&
      jupyter nbconvert --to pdf your_notebook.ipynb'

  install_tex_packages:
    vars:
      PACKAGES: 'tcolorbox pgf xcolor environ trimspaces mathpazo parskip adjustbox collectbox eurosym ecs ucs enumitem ulem mathrsfs jknapltx rsfs collection-fontsrecommended pdfcol caption upquote grffile titling soul'
    cmds:
      - bash -c '
      module purge; module load {{.TEX_MODULE}} &&
      tlmgr update --all --self &&
      tlmgr install {{.PACKAGES}}
      module unload {{.TEX_MODULE}}'